sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  
  #DOCKER_USER
  - secure: "OSmElQI320EYYC+85KvBlxvRbHBYUZJrfvLXMaV9aATJKSUwQrsRqDqsKtnQCz2VyoP20ptlIWM10rh0Ev4alQftUn09b1ABU1BCd3KRdwDBlJFFbgxuHrrfpLXXTF5lyFlkVjdL65cQVSLcDvyZr+GmaXNnTyXK7aIFHkwDCadSoh8utnkY9PReyqkDCvgG5v/pM0w4UsmpSLS/NNbhI2GPQpybIQymIg2ZAfxfraCBdbDnX4FYRQqPZH65qga86rTeU0yIgaJ18UqWevswG56wuwM1jV5wtrLWo3E/jrBjDlBvPz5OUR8OdN1q7boI8yf8Scy037t9pHWKjPxQVhRxU88sx5iRQjj4csVMlXIfOXiSrLHCiZUlAJYRoGaGItALp4icGIW+cyDwx7HdaDgpiacNvJzwoaM9wR+5PduWRk6/JYWuBITHLoELjHqrhPWPFPPZS0TBTnl5CR0530HmZVNQPXuCtzgPdr87No5FpLikf/8477TrVr4MxYblxTRE2r2Dhol7uxlmRsERHjCHunIfnysWUdRaWscUUA8LGLp8pSkYyLYOzkXgfUN8q6/Z5bjGRTewua6SCiBLAmRD+Cm/XYIcBOAzBOsw01Pb24X9LJ81ZeEBJBbfrWTQWIgP8/pzK9e8SxH7p8PF/PpfoVmlJQgEPRiaGq4SXDI="

  #DOCKER_PASSWORD
  - secure: "czduBba2v7JTiPkIeBGbzX6Q44k8OmAjlvSRQK88tlzWdd6x1ByqNf+R51OPzshhYt39HlhHjeSG7TxNK2KSqGCsbgn9awJEu1svi8tjRcvvkyITkeYBzIe5rJcKaOgAVBeCFxOMizp8uK/W2ujChxvDWLGZ2lEpJVVwG/rVGjfz4IDXsg16okBHcNEk+XubBO6hzn72dfhAk/IBpMJqbh1WawVJC/eX1QKs4JNNkr4EZcAb/2gMpfHN2pq+OW4Y46zywMI/Z316LkaNewCOgOLGLiFlVX/WRJU78jr7C//QF82/jpoi3HwqtTeVt2D/c0TiIjrhDsPQa32JZvSbTk8zkPG/bArevt2eJfSfq27ZE68s59uvJuC4rde0Ikp2k3i7mXWDCQP1XT0rizi9XHGpJl1LeifcfJ8kuRU+0imG3FFn0Sf8IsppbY3SwYxtNO7CZaSfGLnMS5iNBW2wXD7h6czkwu5BwmP4lq6/XdI0CENdDDCmpQee19aEkd1rSZ6t32EJreeg1C7gpSWA8b0LzAZ0QNfWTmKEZfxY5A+Q1fgTKWgaKNXr4wUPS0d/Oy3nAmY0r6P1rBhsWjbueJsWzUgW5CcTj0rpYr2RTdql0HdOo/3kySDylwJgs8M0BY1WPU3A5a5CKbGaaJohsHqQyVObtNlK4Ap9UbbJD0Y="

branches:
  only:
  - master

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version
  - SERVICE=$SERVICE make ensure-dependencies
  - docker ps
  - sleep 3

script:
  - make qa
  - TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make brand
  - DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make build

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker